--- 
document-type: "Lecture Notes"
title: "Mathematics of the Actuarial Sciences"
subtitle: "A comprehensive outline of actuarial maths"
author: "Joakim Bilyk"
date: '`r stringr::str_to_sentence(format(Sys.time(), "%B %d, %Y"))`'
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
url: "joakim-bilyk.github.io/books/theory"
preface: |
  This book contains a comprehensive outline of theory on probability theory and mathematical statistics applied in finance, life insurance and non-life insurance. The notes outlines the contents of the major courses regarding the mathematics behind the markov models in life insurance including valuation of financial contracts under the market measure $\mathbb Q$ and the statistical methods used in non-life insurance when estimating the equivalence premium that is the expected expenses of the insurance contract.
  
  The notes are structured as follows: The notes are divided into three parts. The first part is called *The Mathematics of Life Insurance and Financial Contracts* and revolves around payment streams and a market consistent valuation of these. This is indeed the main topics of life insurance and mostly all efforts in this field work towards more robust and/or consistent valuation methods. The second part is called *The Mathematics and Methods of Non-Life Insurance*. In this part we outline the stochastic models behind claim arrivals in homogeneous portfolios and estimation of the premium. We also partly focus on risk management as methods in this field relate somewhat to the non-life field. The third part of the notes outlines some of the mathematics behind the mathematical fundamental taken *as given* in the first two parts. This include the fundamental theory of random variables, measure theory, markov chains and stochastic processes including stochastic calculus.
  
  **The Mathematics of Life Insurance and Financial Contracts**
  
  Life insurance contracts are stochastic payments between two parties agreed upon in advance. These differ from financial contracts in the sense that the issuer of the contract i.e. the insurance company takes on the risk associated with the buyer of the contracts life events and in financial contracts the issuer typically a bank or financial institution takes on some risk associated with a price fluctuation. In recent years, the *unit-link contract* has become the norm in the pension field and so life insurance today have some overlap with banking sector. The valuation of the payments in the life contract is evaluated under the market measure and priced such that there is no arbitrage in the market extended with the life insurance contract. Therefore, the study of market valuation from financial mathematics plays an integral role in the actuarial endeavors.
  
  This first part of the book, starts out with an introduction to the ideas around payment streams, interest, mortality, markov chains and reserves. This is done in the chapter *Basic Life Insurance Mathematics*. Afterwards, in the chapter *Stochastic Processes in Life Insurance Mathematics* we formalize the stochastic processes behind the payment process by considering CADLAG processes that is of finite variations (FV-functions). This will lead us to an extended version of the integral where we allow to integrate with respect to payment streams and other FV-functions. It turns out that the maths around the expected value of such integrals is a bit more complicated than one would let on.
  
  The following two chapters start with an introduction into the mathematics of continuous finance and the theory of arbitrage free valuation of derivatives. This is used afterwards used in the chapter *Topics in Life Insurance*, where Black Scholes types of PDEs are constructed that describe the statewise reserves. However before this we introduce a matrix approach to life insurance and some interest theory. For the definition of the product integral see the appendix.
  
  **The Mathematics and Methods of Non-Life Insurance**
  
  Non-life mathematics revolves around policies where the insurance company takes upon themselves the economic risk arising from events that insured may encounter. The essential here is that these risk cannot be any that offers risk taking of life based risks for instance pensions or sickness and death. As such non-life insurance is insurance of assets or stochastic expenses (for instance court expenses or compensations to third person). Non-life insurance differs significantly from life insurance since the nature of the insurance events is assumed to arrive iid between a homogeneous portfolio of contracts and is often modelled through renewal processes such as the Cramer-Lundberg model. It is the job of the actuarial to determine the theoretical premium of a contract with a certain time exposure (usually one yer), reserve money for claims that are under processing, that may occur in the future or the may already have occurred but not yet reported. To this end the actuarial may deployed a wide range of tools such as generalized linear model or machine learning algorithms for modelling claims arrivals and reserving and estimating probability bounds for the probability of ruin from claims or investments. In this part we also include a chapter on quantitative risk management.
  
  The first chapter, called *Basic Non-Life Insurance Mathematics*, introduces the Poisson process and defines the classical Cramer-Lundberg model. In this chapter we also give some introductory considerations on the ruin probability and estimation methods. The following chapter *Stochastic Processes in Non-Life Insurance Mathematics* gives a deep-dive into the processes behind the claim arrivals in the Cramer-lundberg model, and later the renewal risk model. We finish the chapter by relating the classical renewal risk model to more modern approach including the case with stochastic investment. Lastly, we lay the foundation of claim reserving.
  
  The chapter *Probabilistic Machine Learning* is a introductory chapter on how one may apply machine learning algorithms to tabular data, that is a spreadsheet with $p$ covariates and one response. In this chapter we consider linear models with and without penalties, decision trees including bagging and random forests and neural networks. Lastly, we give some considerations on how one may interpret the results from the ML models discussed earlier. It is common knowledge that ML models are well suited for a wide variety of scenarios but due to their structure we loose alot of interpretability for the linear models (and generalized additive and linear models). Because of this one has to somehow figure out what the model does and how it treats say gender. This is also something we dig into, as we want to debias a potential biassed model (bias may arise from the data itself).
  
  The final chapter on risk management is an introduction to risk measures such as Value-At-Risk and expected shortfall and elliptical and heavy-tailed distributions. In investments we often see a concentration of returns around the mean and then a heavy tail of losses and or gains. This is important when one calculates the capital needed in order to sustain large losses that may arise during a crisis. It is furthermore, an accepted truth that investment are correlated in the sense that they tend to get large together. This is why elliptical distributions are studied. The final sections of this chapter is on credit risk and operational risks.
  
  **Mathematical Prerequisites**
  
  This part of the notes are a rough collection of important results from measure theory and theory on stochastic variables.
keywords: |
  probability theory, insurance mathematics, life insurance, non-life insurance, stochastic differential equations.
description: |
  This document contains lecture notes from the courses i attended during my education. The notes mostly contains results from the master courses but there are also included some results from the bachelor as these lay out some of the fundamentals of the mathematics used during the master courses. I want to stress that this is a work in progress and as such is subject to some small and some severy errors. The contents of these notes have not been supervised by anyone other than myself and so, although i an confident in most of the content, i would not take any of the below as clear facts. Always due your own research and derivations to confirm the results.
---

```{r, setup,include=FALSE}
library(knitr)
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(
    fig.show = 'hide',
    results = 'hide',
    echo = FALSE,
    warning=FALSE,
    message = FALSE
  )
} else {
  knitr::opts_chunk$set(
    warning=FALSE,
    message = FALSE
  )
}
library(ggplot2)
library(dplyr)
theme_custom <- function() {
  
  theme_minimal() %+replace%
    
    theme(
      
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(colour = "black", fill=NA),
      axis.ticks = element_line(),
      #axis.line.x = element_line(color = "#C5C5C5"),
      axis.line = element_line(color = "black"),
      #axis.ticks = element_blank(),
      legend.position = "bottom",
      legend.title = element_blank(),
      #plot.background = element_rect(fill='transparent', color=NA),
      
      plot.title = element_text(             #title
                   #family = font,            #set font family
                   size = 16,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = 0,                #left align
                   vjust = 2,
                   color = "black"),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
                   #family = font,            #font family
                   size = 12,
                   color = "black"),               #font size
      
      plot.caption = element_text(           #caption
                   #family = font,            #font family
                    face = "italic",
                   size = 8,                 #font size
                   hjust = 1,
                   color = "black"),               #right align
      
      axis.title = element_text(             #axis titles
                   #family = font,            #font family
                   size = 12,
                   color = "black"),               #font size
      
      axis.text = element_text(              #axis text
                   #family = font,            #axis famuly
                   size = 12,
                   color = "black"),                #font size
      
      axis.text.x = element_text(            #margin for axis text
                    margin=margin(5, b = 10))
      
    )
}
```

`r if (knitr::is_html_output()) '
# Preface {-}

This book contains a comprehensive outline of theory on probability theory and mathematical statistics applied in finance, life insurance and non-life insurance. The notes outlines the contents of the major courses regarding the mathematics behind the markov models in life insurance including valuation of financial contracts under the market measure $\\mathbb Q$ and the statistical methods used in non-life insurance when estimating the equivalence premium that is the expected expenses of the insurance contract.

The notes are structured as follows: The notes are divided into three parts. The first part is called *The Mathematics of Life Insurance and Financial Contracts* and revolves around payment streams and a market consistent valuation of these. This is indeed the main topics of life insurance and mostly all efforts in this field work towards more robust and/or consistent valuation methods. The second part is called *The Mathematics and Methods of Non-Life Insurance*. In this part we outline the stochastic models behind claim arrivals in homogeneous portfolios and estimation of the premium. We also partly focus on risk management as methods in this field relate somewhat to the non-life field. The third part of the notes outlines some of the mathematics behind the mathematical fundamental taken *as given* in the first two parts. This include the fundamental theory of random variables, measure theory, markov chains and stochastic processes including stochastic calculus.

**The Mathematics of Life Insurance and Financial Contracts**

Life insurance contracts are stochastic payments between two parties agreed upon in advance. These differ from financial contracts in the sense that the issuer of the contract i.e. the insurance company takes on the risk associated with the buyer of the contracts life events and in financial contracts the issuer typically a bank or financial institution takes on some risk associated with a price fluctuation. In recent years, the *unit-link contract* has become the norm in the pension field and so life insurance today have some overlap with banking sector. The valuation of the payments in the life contract is evaluated under the market measure and priced such that there is no arbitrage in the market extended with the life insurance contract. Therefore, the study of market valuation from financial mathematics plays an integral role in the actuarial endeavors.

This first part of the book, starts out with an introduction to the ideas around payment streams, interest, mortality, markov chains and reserves. This is done in the chapter *Basic Life Insurance Mathematics*. Afterwards, in the chapter *Stochastic Processes in Life Insurance Mathematics* we formalize the stochastic processes behind the payment process by considering CADLAG processes that is of finite variations (FV-functions). This will lead us to an extended version of the integral where we allow to integrate with respect to payment streams and other FV-functions. It turns out that the maths around the expected value of such integrals is a bit more complicated than one would let on.

The following two chapters start with an introduction into the mathematics of continuous finance and the theory of arbitrage free valuation of derivatives. This is used afterwards used in the chapter *Topics in Life Insurance*, where Black Scholes types of PDEs are constructed that describe the statewise reserves. However before this we introduce a matrix approach to life insurance and some interest theory. For the definition of the product integral see the appendix.

**The Mathematics and Methods of Non-Life Insurance**

Non-life mathematics revolves around policies where the insurance company takes upon themselves the economic risk arising from events that insured may encounter. The essential here is that these risk cannot be any that offers risk taking of life based risks for instance pensions or sickness and death. As such non-life insurance is insurance of assets or stochastic expenses (for instance court expenses or compensations to third person). Non-life insurance differs significantly from life insurance since the nature of the insurance events is assumed to arrive iid between a homogeneous portfolio of contracts and is often modelled through renewal processes such as the Cramer-Lundberg model. It is the job of the actuarial to determine the theoretical premium of a contract with a certain time exposure (usually one yer), reserve money for claims that are under processing, that may occur in the future or the may already have occurred but not yet reported. To this end the actuarial may deployed a wide range of tools such as generalized linear model or machine learning algorithms for modelling claims arrivals and reserving and estimating probability bounds for the probability of ruin from claims or investments. In this part we also include a chapter on quantitative risk management.

The first chapter, called *Basic Non-Life Insurance Mathematics*, introduces the Poisson process and defines the classical Cramer-Lundberg model. In this chapter we also give some introductory considerations on the ruin probability and estimation methods. The following chapter *Stochastic Processes in Non-Life Insurance Mathematics* gives a deep-dive into the processes behind the claim arrivals in the Cramer-lundberg model, and later the renewal risk model. We finish the chapter by relating the classical renewal risk model to more modern approach including the case with stochastic investment. Lastly, we lay the foundation of claim reserving.

The chapter *Probabilistic Machine Learning* is a introductory chapter on how one may apply machine learning algorithms to tabular data, that is a spreadsheet with $p$ covariates and one response. In this chapter we consider linear models with and without penalties, decision trees including bagging and random forests and neural networks. Lastly, we give some considerations on how one may interpret the results from the ML models discussed earlier. It is common knowledge that ML models are well suited for a wide variety of scenarios but due to their structure we loose alot of interpretability for the linear models (and generalized additive and linear models). Because of this one has to somehow figure out what the model does and how it treats say gender. This is also something we dig into, as we want to debias a potential biassed model (bias may arise from the data itself).

The final chapter on risk management is an introduction to risk measures such as Value-At-Risk and expected shortfall and elliptical and heavy-tailed distributions. In investments we often see a concentration of returns around the mean and then a heavy tail of losses and or gains. This is important when one calculates the capital needed in order to sustain large losses that may arise during a crisis. It is furthermore, an accepted truth that investment are correlated in the sense that they tend to get large together. This is why elliptical distributions are studied. The final sections of this chapter is on credit risk and operational risks.

**Mathematical Prerequisites**

This part of the notes are a rough collection of important results from measure theory and theory on stochastic variables.

'`

# Introduction {-}

## Abbreviations {-}

Below is given the abbreviations used when referencing to books:

| Chapter | Abbreviation | Source |
| :---- | :-- | :----------------- |
| Basic Life Insurance Mathematics | Ragnar | *Basic Life Insurance Mathematics* by Ragnar Norberg (2002) |
| Stochastic Processes in Life Insurance Mathematics | Lund | *Stochastic Processes in Life Insurance*: The Dynamic Approach by Jesper Lund Pedersen (2022)|
| Topics in Life Insurance Mathematics  | Asmussen | *Risk and Insurance*: A Graduate Text by Soren Asmussen and Mogens Steffensen (2020). |
| | Bladt | Notes from lectures in Liv2. |
| Continuous Time Finance | Bjork | *Arbitrage Theory in Continuous Time (Fourth edition)* by Thomas Bjork, Oxford University Press (2019). |
| Basic Non-Life Insurance Mathematics | Mikosch | *Non-Life Insurance Mathematics* by Thomas Mikosch (2006). |
| Stochastic Processes in Life Insurance Mathematics | Schmidli | *Lecture Notes on FM2* by Hanspeter Schmidli. |
| Topics in Non-Life Insurance Mathematics | Paulsen | *Non-life Insurance* by Jostein Paulsen (2023) |
| Probabilistic Machine Learning | *None* | Slides from lectures. |
| Quantative Risk Management | McNeil | *Quantitative Risk Management* by McNeil. (2015) |
| Measure Theory | Bjork | *Arbitrage Theory in Continuous Time (Fourth edition)* by Thomas Bjork, Oxford University Press (2019). |
| | Protter | *Probability Essentials (2. edition)* by Jean Jacod and Philip Protter (2004). |
| Random Variables | Bjork | *Arbitrage Theory in Continuous Time (Fourth edition)* by Thomas Bjork, Oxford University Press (2019). |
| | Hansen | *Stochastic Processes* (2. edition) by Ernst Hansen (2021). |
| Discrete Time Stochastic Processes | Hansen | *Stochastic Processes* (2. edition) by Ernst Hansen (2021). |
| Continuous Time Stochastic Processes | Bjork | *Arbitrage Theory in Continuous Time (Fourth edition)* by Thomas Bjork, Oxford University Press (2019). |
| Stochastic Calculus | Bjork | *Arbitrage Theory in Continuous Time (Fourth edition)* by Thomas Bjork, Oxford University Press (2019). |
| | Bladt | Notes from lectures in Liv2. |
| Linear Algebra | Wiki | Wikipedia |

## To-do reading {-}

| Week | Course | Chapter | X |
| :- |  :---- | :-------- | :-: |
| 1 | QRM       | Finish risk measures                  |  |
|   | Liv1      | Chapter 1-3                           | X |
|   | StokLiv   | Chapter 1-4                           | X |
|   | ProjLiv   | Buchardt & Moeller (2015)             |  |
|   | Skade1    | Chapter 1-2.1                         | X |
|   | SkadeStok | Chapter 1-2 (Schmidli)                | X |
|   | Skade2    | Chapter 4 + 6                         |  |
| 2 | QRM       | Extreme value theory with heavy tails; Hill estimator; POT method.            | |
|   | Liv1      | Chapter 4                             | |
|   | StokLiv   | Chapter 6-11                          | |
|   | ProjLiv   | Buchardt, Furrer, Sandqvist (2023)    | |
|   | Skade1    | Chapter 2.2-2.3                       | |
|   | SkadeStok | Chapter 3 (Schmidli)                  | |
|   | Skade2    | TBD                                   | |
| 3 | QRM       | Multivariate distributions and dependence. Elliptical distributions; copula | |
|   | Liv1      | Chapter 5-6                           | |
|   | StokLiv   | Chapter 12, 14-16                     | |
|   | ProjLiv   | TBD                                   | |
|   | Skade1    | Chapter 3.1-3.2                       | |
|   | SkadeStok | Notes on stochastic investments       | |
|   | Skade2    | TBD                                   | |
| 4 | QRM       | Credit risk modelling                 | |
|   | Liv1      | Chapter 7                             | |
|   | StokLiv   | Chapter 17-18                         | |
|   | ProjLiv   | TBD                                   | |
|   | Skade1    | Chapter 3.3-3.4                       | |
|   | SkadeStok | Claims reserving                      | |
|   | Skade2    | TBD                                   | |
| 5 | QRM       | Models for operational risk.          | |
|   | Liv1      | Chapter 10                            | |
|   | StokLiv   | Chapter 20-22                         | |
|   | ProjLiv   | TBD                                   | |
|   | Skade1    | Chapter 4                             | |
|   | Skade2    | TBD                                   | |
| 6 | StokLiv   | Chapter 23                            | |
|   | ProjLiv   | TBD                                   | |
|   | Skade1    | Chapter 5                             | |
|   | Skade2    | TBD                                   | |
| 7 | StokLiv   | Chapter 24                            | |
|   | ProjLiv   | TBD                                   | |
|   | Skade1    | Chapter 6                             | |
|   | Skade2    | TBD                                   | |

## Notation {-}

We use the following shorthand notation.

| Symbol | Interpretation |
| :-: | :------ |
| $f(t-)=f_{t-}$ | $\lim_{s\ \nearrow\ t}f(s)$ being the left limit of $f$ |
| $f(t+)=f_{t+}$ | $\lim_{s\ \searrow\ t}f(s)$ being the right limit of $f$ |
| $\Delta f(t)$ | $f(t)-f(t-)$ being the jump function of $f$ |
| $\int_0^t r$ | $\int_0^tr(u)\ du$. |
